services:
    web:
        build:
            context: .
            dockerfile: ./docker/production/Dockerfile
            target: production
            args:
                - APP_ENV=production
                - APP_DEBUG=false
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
        ports:
            - 8080:8080
