[supervisord]
nodaemon=true
user=root

[program:cache-config]
command=php /var/www/html/laravel-chirper/artisan config:cache
autostart=true
autorestart=false
startsecs=0
priority=1

[program:restarting-queue]
command=php /var/www/html/laravel-chirper/artisan queue:restart
autostart=true
autorestart=false
startsecs=0
priority=1

[program:scheduler]
command=php /var/www/html/laravel-chirper/artisan schedule:run
autostart=true
autorestart=true
stdout_logfile=/tmp/cron_log.log

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/laravel-chirper/artisan queue:work  --tries=3 --daemon
autostart=true
autorestart=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/worker.log
stderr_logfile=/var/log/worker_error.log

[program:laravel-server]
command=php artisan serve --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/server.log
